"use client";
import { useRef, useState, type FormEvent } from "react";
import { useWalletSession } from "@/hooks/useWalletSession";
import { isE2eTestMode, readE2eWalletOverride } from "@/lib/e2e/browserWallet";
import type { ProxyResult } from "@/server/research/proxy-inspector";
import { ContractInput } from "./ContractInput"; import { ImplementationGraph } from "./ImplementationGraph"; import { AuthorityTable } from "./AuthorityTable"; import { ProxyEvidence } from "./ProxyEvidence";
export function ProxyInspector() {
  const wallet = useWalletSession(); const override = isE2eTestMode() ? readE2eWalletOverride() : null; const [network, setNetwork] = useState("goat"); const [address, setAddress] = useState(""); const [view, setView] = useState<{ scope: string; result?: ProxyResult; error?: string; busy: boolean }>({ scope: "", busy: false }); const generation = useRef(0); const owner = wallet.family === "evm" ? wallet.address : override?.family === "evm" ? override.address : undefined; const scope = owner + ":" + network;
  async function submit(event: FormEvent) { event.preventDefault(); if (!owner) return; const token = ++generation.current; setView({ scope, busy: true }); try { const response = await fetch("/api/insights/proxy-inspector", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ walletAddress: owner, network, walletNetwork: network, contractAddress: address }) }); const body = await response.json() as ProxyResult & { error?: string }; if (token !== generation.current) return; if (!response.ok && !body.state) throw new Error(body.error ?? "Inspection failed"); setView({ scope, result: body, busy: false }); } catch (error) { if (token === generation.current) setView({ scope, error: error instanceof Error ? error.message : "Inspection failed", busy: false }); } }
  const result = view.scope === scope ? view.result : undefined;
  return <div className="space-y-6"><header><div className="text-xs uppercase text-[#d9a441]">EVM insight</div><h1 className="text-3xl font-semibold">Proxy implementation inspector</h1><p className="text-sm text-white/55">Read standardized proxy evidence without upgrade or signing actions.</p></header>{!owner ? <div role="status">Connect an authenticated EVM wallet.</div> : null}<form onSubmit={submit} className="glass-panel grid gap-4 rounded-2xl p-5"><ContractInput address={address} network={network} busy={!owner || view.busy} onAddress={setAddress} onNetwork={(value) => { generation.current += 1; setNetwork(value); }} /></form>{view.error ? <div role="alert">{view.error}</div> : null}{result ? <><div><strong>{result.classification}</strong> · {result.state}</div><ImplementationGraph result={result} /><AuthorityTable result={result} /><ProxyEvidence result={result} /></> : null}</div>;
}
