import assert from "node:assert/strict";
import { applyStressScenario } from "../src/server/portfolio/stress";
import { STRESS_SCENARIOS } from "../src/server/portfolio/scenarios";
import type { PortfolioSnapshot, TokenHolding } from "../src/server/types";
const holding = (overrides: Partial<TokenHolding>): TokenHolding => ({ symbol: "ETH", tokenAddress: "0x1", chainId: "ethereum", balance: 10, priceUsd: 10, valueUsd: 100, allocationPercent: 50, ...overrides } as TokenHolding);
const snapshot = (holdings: TokenHolding[]) => ({ holdings, totalValueUsd: holdings.reduce((sum, h) => sum + h.valueUsd, 0), riskScore: 20 } as PortfolioSnapshot);
const base = snapshot([holding({}), holding({ symbol: "USDC", priceUsd: .8, valueUsd: 8 })]);
const before = JSON.stringify(base);
const result = applyStressScenario(base, STRESS_SCENARIOS[0]);
assert.equal(result.stressedSnapshot.holdings[1].priceUsd, .8, "A market crash must not restore a depegged stablecoin to $1");
assert.equal(result.delta.stressedValueUsd, 88);
assert.equal(result.stressedSnapshot.holdings[0].allocationPercent, 80 / 88 * 100);
assert.equal(JSON.stringify(base), before);
assert.deepEqual(result, applyStressScenario(base, STRESS_SCENARIOS[0]));
const native = snapshot([holding({ symbol: "XLM" }), holding({ symbol: "ETH", assetKind: "native" }), holding({ symbol: "XLM", chainId: "stellar-pubnet", assetKind: "classic" }), holding({ symbol: "XLM", chainId: "stellar-pubnet", assetKind: "native" })]);
const stressed = applyStressScenario(native, { id: "native", version: 1, name: "Native", description: "", changes: [{ type: "price_multiplier", target: "stellar_native", multiplier: .5 }] });
assert.deepEqual(stressed.stressedSnapshot.holdings.map(h => h.priceUsd), [10, 10, 10, 5]);
const unknown = holding({ priceUsd: null, valueUsd: 0 });
assert.equal(applyStressScenario(snapshot([unknown]), STRESS_SCENARIOS[0]).stressedSnapshot.holdings[0].priceUsd, null);
assert.equal(applyStressScenario(snapshot([]), STRESS_SCENARIOS[0]).delta.stressedValueUsd, 0);
console.log("Stress targeting checks passed");
